# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Create Downloads directory
      run: mkdir -p /Users/runner/Downloads
      
    - name: Setup GoogleService-Info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > /Users/runner/Downloads/GoogleService-Info.plist
      
    - name: Build
      run: |
        xcodebuild clean build \
          -scheme FitnessProject \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
