# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Setup GoogleService-Info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > FitnessProject/GoogleService-Info.plist
      
    - name: Build and Test
      run: |
        xcodebuild test -scheme FitnessProject \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: |
          build/reports/
          *.xcresult
